### ISSUE TITLE
textfield does not get proper start height if not visible initially

### ISSUE THREAD

**Issue by cjblomqvist** [BBWeb/d-md-components#17]
Solution for when field is empty: Set height to auto if scrollHeight === 0. However, we still don't have a solution for whenever there's a lot of text in the field (as auto only goes so far in such scenarios). One solution to this is to say in the README that the user needs to trigger a function whenever the textarea becomes visible. atm. there is no publicly facing method for this (although _maybeExpand exists - aka. there should be an action for that with a good name).

Further, it would be nice to be able to specify if the textarea should auto-adjust it's height or not.

**Comment by cjblomqvist** [comment]
the workaround in practice:
this.textarea._maybeExpand(this.textarea.textarea);
(assuming the textfield component is saved as="textarea"

**Comment by sjovik** [comment]
Fixed in #28
