### ISSUE TITLE
Implement persistent helper text

### ISSUE THREAD

**Issue by cjblomqvist** [BBWeb/d-md-components#20]
At the absolute bottom of https://www.google.com/design/spec/components/text-fields.html#text-fields-required-fields there's a video, where one field has a persistent help text. We should implement support for this. The need rose form a real scenario in one of our projects. I concluded to remove it until we have this solution for it. There are still some questions about what to with errors in such scenario (we should probably discuss), but I can imagine that this will popup again.

**Comment by cjblomqvist** [comment]
Haven't you already implemented this @sjovik ?

**Comment by sjovik** [comment]
Yes, this is done, it won't resize the textfield still (neither does error messages btw) if the message overflows but i think that can be intended
